Harness with libfuzzer
mayhemheroes/libriscv pull request #1
Opened 2022-04-28 20:10 UTC by jeff14994

2022-05-05 06:37 UTC, xansec requested changes
It looks like you've taken the repository and copied it in its entirety underneath the `/fuzz` directory. This won't work, will unnecessarily duplicate code, and confuse the upstream maintainers. I would recommend trying to start again with this target, adding only one or a couple of files. The bare minimum you should need is

1. A Dockerfile
2. A Mayhemfile
3. A mayhem.yml (for github/workflows)
4. A fuzz target 

The bare minimum you should have to do is described here in this subfolder:
https://github.com/fwsGonzo/libriscv/tree/master/fuzz

If you see there, the `fuzzer.sh` builds the target for you. All you need to do is run this command in your Dockerfile (during the build stage), and then copy the relevant fuzz target (or targets) to the package stage. Finally, create one or more Mayhemfiles referencing each fuzz target.

I would recommend closing this PR and resubmitting.

2022-05-05 06:37 UTC, xansec commented on CMakeLists.txt
> +cmake_minimum_required(VERSION 3.9)
Did you add a new `CMakeLists.txt` or move the existing one to a new location?

2022-05-05 06:37 UTC, xansec commented on fuzz.cpp
> +#include <libriscv/machine.hpp>
Was this written from scratch or copied from somewhere? `fuzz.cpp` is not a very descriptive filename.

2022-05-05 06:37 UTC, xansec commented on helpers.cpp
> +#include <climits>
This file also seems to have been moved?

2022-05-29 21:42 UTC, xansec commented
Please update this PR or we will have to close.

2022-06-01 15:12 UTC, jeff14994 commented
okay, i'm working on it

2022-06-29 08:14 UTC, closed without merging